version: '3.8'
services:
  node-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_NAME}-${ENV}-CONTAINER
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
      - "${FRONT_END_PORT}:${FRONT_END_PORT}"
    volumes:
      - ../:/app
    depends_on:
      - mongo
    command: /bin/bash -c "chmod +x /app/docker/run.sh && /app/docker/run.sh ${ENV}"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - FRONT_END_PORT=${FRONT_END_PORT}
      - VITE_SERVER_EXPRESS_URI=${VITE_SERVER_EXPRESS_URI}
      - SERVER_URI=${SERVER_URI}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
  mongo:
    image: mongo:latest
    container_name: ${APP_NAME}-MONGO-${ENV}-CONTAINER
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ../init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MOCK_USERS_PASSWORD=${MOCK_USERS_PASSWORD}

volumes:
  mongodb-data:
    driver: local
